---
language: ruby
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
services: docker
if: (type = pull_request) OR (tag IS present) OR (branch = master)
# Don't `bundle install` which takes about 1.5 mins
env:
  matrix:
  - INSTANCE=debian-8
  - INSTANCE=debian-9
  - INSTANCE=ubuntu-1404
  - INSTANCE=ubuntu-1604
install: echo "skip bundle install"
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
script: kitchen verify ${INSTANCE}
matrix:
  include:
    - script: chef exec delivery local all
      env: UNIT_AND_LINT=1
